### ISSUE TITLE
hashicorp vault support

### ISSUE THREAD

**Issue by mcollina** [nearform/fastify-secrets-core#58]
We should build another secrets module for hashicorp vault: https://www.vaultproject.io/

**Comment by simoneb** [comment]
this is basically another implementation similar to the ones we already have, which are described on the blog https://www.nearform.com/blog/uncovering-secrets-in-fastify/

**Comment by mcollina** [comment]
Yes exactly

**Comment by penx** [comment]
I have something working at https://github.com/nearform/fastify-secrets-hashicorp
