### ISSUE TITLE
CI configs

### ISSUE THREAD

**Issue by mcollina** [nearform/fastify-secrets-core#59]
It seems Github Actions are not currently run for each commit landed on master

**Comment by Peterabsolon** [comment]
@mcollina From what I see they are. What makes you think that's not the case?

The workflow configuration seems pretty standard:

```
name: CI
on: [push, pull_request]
```

Actions tab seems to confirm this is the case too.

![image](https://user-images.githubusercontent.com/5757143/107781037-b911f700-6d47-11eb-96b1-285433afe926.png)

Maybe you meant that they should run for each _commit_, not just push that may multiple and is run just once?

**Comment by mcollina** [comment]
![Screenshot 2021-02-12 at 15 44 44](https://user-images.githubusercontent.com/52195/107782381-49047080-6d49-11eb-8006-b323751b23b0.png)


There should be a green tick (or red cross) near the commit:

![Screenshot 2021-02-12 at 15 45 43](https://user-images.githubusercontent.com/52195/107782465-65081200-6d49-11eb-809d-1e9a47248bf3.png)

**Comment by Peterabsolon** [comment]
@simoneb cc @mcollina This seems to be an issue with https://github.com/fastify/github-action-merge-dependabot. @salmanm is taking a look at it.

The thing worked as it was supposed to up until this commit - https://github.com/nearform/fastify-secrets-core/commit/a4f683c9d4bb18a84d4125fd7f5cd1ce04a3f4ee

The builds are getting triggered but somehow are not matched with what's getting merged. Or something among those lines.

**Comment by mcollina** [comment]
That might well be the case: https://github.com/fastify/fastify-nextjs has the same issue apparently.

**Comment by penx** [comment]
From what I can tell, PRs that are auto merged by `github-action-merge-dependabot` are done so by the github-actions bot.

GitHub actions don't seem to trigger for commits that are made by the github-actions bot, I think to avoid potential infinite loops.

I think if `github-action-merge-dependabot` is configured to use a github-token other than the one that is provided by Github Actions, then this should fix it.

Perhaps GitHub actions docs have some more info/workarounds for this (I haven't been able to find any, yet)

**Comment by penx** [comment]
Ah here's the docs:

https://docs.github.com/en/actions/reference/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token

**Comment by penx** [comment]
There's a thread about a very similar issue here

https://github.com/peter-evans/create-pull-request/issues/48

Which links to this list of possible alternatives to a personal access token:

https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md#workarounds-to-trigger-further-workflow-runs

I think creating a GitHub app for `github-action-merge-dependabot` sounds like a good option.

**Comment by simoneb** [comment]
Good catch @penx. Do you have any idea why this worked until a certain point and then stopped working? I believe this can be seen in the history of actions executions.

**Comment by simoneb** [comment]
> I think creating a GitHub app for `github-action-merge-dependabot` could be a good option.

unfortunately it isn't, because a github app needs to be installed and it's a lot more work

**Comment by penx** [comment]
> Do you have any idea why this worked until a certain point and then stopped working?

As far as I can see [here](https://github.com/nearform/fastify-secrets-core/commits/master), dependabot PRs up until 10 Nov 2020 have the green tick and [were being merged manually](https://github.com/nearform/fastify-secrets-core/pull/22).

Dependabot auto merge was added on 10 Nov 2020, and since then there have been no green ticks next to dependabot PRs.

**Comment by penx** [comment]
Closed as won't fix after discussion with @simoneb
